### ISSUE TITLE
Can't remove DEV adware installed on Pop OS

### ISSUE THREAD

**Issue by aindriu80** [pop-os/launcher#151]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

![2022-12-29_16-21](https://user-images.githubusercontent.com/8885837/209981385-0b3d4a02-297f-4db5-b42c-65fe2db787ee.png)

**Issue/Bug Description:**

Can't get rid of annoying **DEV** adware

**Steps to reproduce (if you know):**
Type the word dev and adware comes up.  I never installed it on my machine but can't remove it, 

**Expected behavior:**

No **DEV** Adware

**Other Notes:**

It should be easily removed not baked into the OS

**Comment by aindriu80** [comment]
i keep deleting the entry in `/usr/lib/pop-launcher/plugins/web/config.ron` but it comes back after I update POP, there is something installed somewhere that adds the entry to config.ron.  Can you tell what that is please?

**Comment by n3m0-22** [comment]
It is part of the web plugin. It will always get the newest configuration `config.ron` when `pop-laucher` updates. I just tested a way that seems to accomplish what you want and should persist between updates.

In the directory `~/.local/share/pop-launcher/plugins/web/` edit the `config.ron` file to contain the following. 

```
(
    rules: [
        (
            matches: ["dev"],
            queries: [(name: "", query: "")],
        ),   
    ]
)

```

This new empty rule takes precedence so that when you type `dev` in the launcher it wont start a search for `https://dev.to`.

If there are other entries that bother you you can add empty rules for them as well.

```
 (
    rules: [
        (
            matches: ["dev"],
            queries: [(name: "", query: "")],
        ),
        (
            matches: ["gs"],
            queries: [(name: "", query: "")],
        ), 
        (
            matches: ["ddg"],
            queries: [(name: "", query: "")],
        ),    
    ]
)
```
This will allow the web plugin to still work and make it easy to revert if you change your mind. For instance if you want `ddg` with the above example either delete the entire entry or just remove the value in quotes for match.

Example:

`matches: ["ddg"],` becomes `matches: [""],`

**Comment by aindriu80** [comment]
thanks,, I'm at the stage now where I had to write a bash script to copy config.ron over when the system gets updated.
