### ISSUE TITLE
Can't see highlighted item

### ISSUE THREAD

**Issue by PanZWarzywniaka** [pop-os/launcher#226]
Hi all,

Pop-os newbie here.

After an system update I can't see (bearly see) the highlighted item in the launcher:

![image](https://github.com/pop-os/launcher/assets/38562250/16790c22-b31a-4188-b663-b85483fd5e32)

Does anyone know why is that?

**Comment by leviport** [comment]
It's usually a theme thing. Toggling between light mode and dark mode in Settings might help. If not, you can probably fix it by installing gnome-tweaks and fiddling with the color theme settings in there.

**Comment by Hi-Angel** [comment]
Not the OP, but just built/installed the launcher from git and was about to report same problem.

> It's usually a theme thing.

FTR, given everything else looks okay, I'd presume it's the launcher's bug rather than theme misconfiguration.

> Toggling between light mode and dark mode in Settings might help. 

Tried clicking the `Dark Style` in the tray, but it has no influence of the `pop-launcher`'s appearance.

> If not, you can probably fix it by installing gnome-tweaks and fiddling with the color theme settings in there.

Tried looking at it, but there's not much to change really. This is my current config

![image](https://github.com/pop-os/launcher/assets/7935057/f2667661-c7bf-42f7-9976-c1438d04b120)

Tried changing `Icons` and `Legacy Applications`, but again that has no influence on the launcher's look.

**Comment by Hi-Angel** [comment]
Hmm, trying to look through repository for keywords `themes`, `foreground`, `Type to search apps`, but I see nothing related whatsoever. Advises for where to look for theme configuration in the launcher code are welcome.

**Comment by PanZWarzywniaka** [comment]
Tried to look again into this and fully agree with @Hi-Angel,
Changing back to light theme doesn't help either, and couldn't find a "tweak" where I could change font colour in the launcher.

**Comment by PanZWarzywniaka** [comment]
Ok I managed to solve the problem using [this issue](https://github.com/pop-os/shell/issues/132#issuecomment-989250527)
by enabling [user themes extension](https://askubuntu.com/questions/545741/why-is-shell-theme-disabled-in-gnome-tweak-tool)
